export const refs = {
  selectCountryBtn: document.getElementById('select-country-btn'),
  searchForm: document.querySelector('.search-form'),
  input: document.getElementById('output'),
  eventList: document.querySelector('.card-list'),
  preloader: document.querySelector('.preloader'),
  countryList: document.querySelector('.country-list'),
  countryBtnList: document.querySelectorAll('li'),
  pagination: document.getElementById('pagination'),
  modal: document.querySelector('.modal'),
  backdropModal: document.querySelector('.backdrop'),
  body: document.querySelector('body'),
  signInBtn:document.querySelector('.sign-in-btn'),
authContainer:document.querySelector('.auth-container'),
authBg:document.querySelector('.auth-bg'),
};
